/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* top =  1  *)
(* src = "sbox.v:1.1-543.10" *)
module sbox(clk, i0_0, i0_1, i1_0, i1_1, i2_0, i2_1, i3_0, i3_1, i4_0, i4_1, i5_0, i5_1, i6_0, i6_1, i7_0, i7_1, dec_1, rand_6, rand_3, rand_8
, rand_11, rand_2, rand_7, rand_1, rand_4, rand_9, rand_10, rand_12, rand_5, o0_0, o0_1, o1_0, o1_1, o2_0, o2_1, o3_0, o3_1, o4_0, o4_1, o5_0, o5_1
, o6_0, o6_1, o7_0, o7_1);
  (* src = "sbox.v:440.5-541.8" *)
  wire _000_;
  (* src = "sbox.v:440.5-541.8" *)
  wire _001_;
  (* src = "sbox.v:440.5-541.8" *)
  wire _002_;
  (* src = "sbox.v:440.5-541.8" *)
  wire _003_;
  (* src = "sbox.v:440.5-541.8" *)
  wire _004_;
  (* src = "sbox.v:440.5-541.8" *)
  wire _005_;
  (* src = "sbox.v:440.5-541.8" *)
  wire _006_;
  (* src = "sbox.v:440.5-541.8" *)
  wire _007_;
  (* src = "sbox.v:440.5-541.8" *)
  wire _008_;
  (* src = "sbox.v:440.5-541.8" *)
  wire _009_;
  (* src = "sbox.v:440.5-541.8" *)
  wire _010_;
  (* src = "sbox.v:440.5-541.8" *)
  wire _011_;
  (* src = "sbox.v:440.5-541.8" *)
  wire _012_;
  (* src = "sbox.v:440.5-541.8" *)
  wire _013_;
  (* src = "sbox.v:440.5-541.8" *)
  wire _014_;
  (* src = "sbox.v:440.5-541.8" *)
  wire _015_;
  (* src = "sbox.v:440.5-541.8" *)
  wire _016_;
  (* src = "sbox.v:440.5-541.8" *)
  wire _017_;
  (* src = "sbox.v:440.5-541.8" *)
  wire _018_;
  (* src = "sbox.v:440.5-541.8" *)
  wire _019_;
  (* src = "sbox.v:440.5-541.8" *)
  wire _020_;
  (* src = "sbox.v:440.5-541.8" *)
  wire _021_;
  (* src = "sbox.v:440.5-541.8" *)
  wire _022_;
  (* src = "sbox.v:440.5-541.8" *)
  wire _023_;
  (* src = "sbox.v:440.5-541.8" *)
  wire _024_;
  (* src = "sbox.v:440.5-541.8" *)
  wire _025_;
  (* src = "sbox.v:440.5-541.8" *)
  wire _026_;
  (* src = "sbox.v:440.5-541.8" *)
  wire _027_;
  (* src = "sbox.v:440.5-541.8" *)
  wire _028_;
  (* src = "sbox.v:440.5-541.8" *)
  wire _029_;
  (* src = "sbox.v:440.5-541.8" *)
  wire _030_;
  (* src = "sbox.v:440.5-541.8" *)
  wire _031_;
  (* src = "sbox.v:440.5-541.8" *)
  wire _032_;
  (* src = "sbox.v:440.5-541.8" *)
  wire _033_;
  (* src = "sbox.v:440.5-541.8" *)
  wire _034_;
  (* src = "sbox.v:440.5-541.8" *)
  wire _035_;
  (* src = "sbox.v:440.5-541.8" *)
  wire _036_;
  (* src = "sbox.v:440.5-541.8" *)
  wire _037_;
  (* src = "sbox.v:440.5-541.8" *)
  wire _038_;
  (* src = "sbox.v:440.5-541.8" *)
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  (* src = "sbox.v:119.10-119.43" *)
  wire a_share_neg_hpc3_w_1_order1_HPC30;
  (* src = "sbox.v:139.10-139.43" *)
  wire a_share_neg_hpc3_w_1_order1_HPC31;
  (* src = "sbox.v:159.10-159.43" *)
  wire a_share_neg_hpc3_w_1_order1_HPC32;
  (* src = "sbox.v:50.11-50.14" *)
  input clk;
  wire clk;
  (* src = "sbox.v:67.12-67.17" *)
  input dec_1;
  wire dec_1;
  (* src = "sbox.v:51.12-51.16" *)
  input i0_0;
  wire i0_0;
  (* src = "sbox.v:52.12-52.16" *)
  input i0_1;
  wire i0_1;
  (* src = "sbox.v:53.12-53.16" *)
  input i1_0;
  wire i1_0;
  (* src = "sbox.v:54.12-54.16" *)
  input i1_1;
  wire i1_1;
  (* src = "sbox.v:55.12-55.16" *)
  input i2_0;
  wire i2_0;
  (* src = "sbox.v:56.12-56.16" *)
  input i2_1;
  wire i2_1;
  (* src = "sbox.v:57.12-57.16" *)
  input i3_0;
  wire i3_0;
  (* src = "sbox.v:58.12-58.16" *)
  input i3_1;
  wire i3_1;
  (* src = "sbox.v:59.12-59.16" *)
  input i4_0;
  wire i4_0;
  (* src = "sbox.v:60.12-60.16" *)
  input i4_1;
  wire i4_1;
  (* src = "sbox.v:61.12-61.16" *)
  input i5_0;
  wire i5_0;
  (* src = "sbox.v:62.12-62.16" *)
  input i5_1;
  wire i5_1;
  (* src = "sbox.v:63.12-63.16" *)
  input i6_0;
  wire i6_0;
  (* src = "sbox.v:64.12-64.16" *)
  input i6_1;
  wire i6_1;
  (* src = "sbox.v:65.12-65.16" *)
  input i7_0;
  wire i7_0;
  (* src = "sbox.v:66.12-66.16" *)
  input i7_1;
  wire i7_1;
  (* src = "sbox.v:98.10-98.14" *)
  wire n1_0;
  (* src = "sbox.v:100.10-100.14" *)
  wire n2_0;
  (* src = "sbox.v:150.9-150.17" *)
  wire n2_0_reg;
  (* src = "sbox.v:101.10-101.14" *)
  wire n2_1;
  (* src = "sbox.v:157.9-157.17" *)
  wire n2_1_reg;
  (* src = "sbox.v:102.10-102.14" *)
  wire n3_0;
  (* src = "sbox.v:130.9-130.17" *)
  wire n3_0_reg;
  (* src = "sbox.v:103.10-103.14" *)
  wire n3_1;
  (* src = "sbox.v:137.9-137.17" *)
  wire n3_1_reg;
  (* src = "sbox.v:104.10-104.14" *)
  wire n6_0;
  (* src = "sbox.v:110.9-110.17" *)
  wire n6_0_reg;
  (* src = "sbox.v:105.10-105.14" *)
  wire n6_1;
  (* src = "sbox.v:117.9-117.17" *)
  wire n6_1_reg;
  (* src = "sbox.v:106.10-106.14" *)
  wire n7_0;
  (* src = "sbox.v:168.10-168.15" *)
  wire nt0_0;
  (* src = "sbox.v:176.9-176.18" *)
  wire nt0_0_reg;
  (* src = "sbox.v:169.10-169.15" *)
  wire nt0_1;
  (* src = "sbox.v:183.9-183.18" *)
  wire nt0_1_reg;
  (* src = "sbox.v:172.10-172.15" *)
  wire nt2_0;
  (* src = "sbox.v:212.9-212.18" *)
  wire nt2_0_reg;
  (* src = "sbox.v:173.10-173.15" *)
  wire nt2_1;
  (* src = "sbox.v:224.9-224.18" *)
  wire nt2_1_reg;
  (* src = "sbox.v:230.10-230.15" *)
  wire nt4_0;
  (* src = "sbox.v:250.9-250.18" *)
  wire nt4_0_reg;
  (* src = "sbox.v:231.10-231.15" *)
  wire nt4_1;
  (* src = "sbox.v:262.9-262.18" *)
  wire nt4_1_reg;
  (* src = "sbox.v:81.17-81.21" *)
  output o0_0;
  wire o0_0;
  (* src = "sbox.v:82.17-82.21" *)
  output o0_1;
  wire o0_1;
  (* src = "sbox.v:276.10-276.18" *)
  wire o0_val_0;
  (* src = "sbox.v:277.10-277.18" *)
  wire o0_val_1;
  (* src = "sbox.v:83.17-83.21" *)
  output o1_0;
  wire o1_0;
  (* src = "sbox.v:84.17-84.21" *)
  output o1_1;
  wire o1_1;
  (* src = "sbox.v:280.10-280.18" *)
  wire o1_val_0;
  (* src = "sbox.v:281.10-281.18" *)
  wire o1_val_1;
  (* src = "sbox.v:85.17-85.21" *)
  output o2_0;
  wire o2_0;
  (* src = "sbox.v:86.17-86.21" *)
  output o2_1;
  wire o2_1;
  (* src = "sbox.v:272.10-272.18" *)
  wire o2_val_0;
  (* src = "sbox.v:273.10-273.18" *)
  wire o2_val_1;
  (* src = "sbox.v:87.17-87.21" *)
  output o3_0;
  wire o3_0;
  (* src = "sbox.v:88.17-88.21" *)
  output o3_1;
  wire o3_1;
  (* src = "sbox.v:282.10-282.18" *)
  wire o3_val_0;
  (* src = "sbox.v:283.10-283.18" *)
  wire o3_val_1;
  (* src = "sbox.v:89.17-89.21" *)
  output o4_0;
  wire o4_0;
  (* src = "sbox.v:90.17-90.21" *)
  output o4_1;
  wire o4_1;
  (* src = "sbox.v:278.10-278.18" *)
  wire o4_val_0;
  (* src = "sbox.v:279.10-279.18" *)
  wire o4_val_1;
  (* src = "sbox.v:91.17-91.21" *)
  output o5_0;
  wire o5_0;
  (* src = "sbox.v:92.17-92.21" *)
  output o5_1;
  wire o5_1;
  (* src = "sbox.v:270.10-270.18" *)
  wire o5_val_0;
  (* src = "sbox.v:271.10-271.18" *)
  wire o5_val_1;
  (* src = "sbox.v:93.17-93.21" *)
  output o6_0;
  wire o6_0;
  (* src = "sbox.v:94.17-94.21" *)
  output o6_1;
  wire o6_1;
  (* src = "sbox.v:268.10-268.18" *)
  wire o6_val_0;
  (* src = "sbox.v:269.10-269.18" *)
  wire o6_val_1;
  (* src = "sbox.v:95.17-95.21" *)
  output o7_0;
  wire o7_0;
  (* src = "sbox.v:96.17-96.21" *)
  output o7_1;
  wire o7_1;
  (* src = "sbox.v:274.10-274.18" *)
  wire o7_val_0;
  (* src = "sbox.v:275.10-275.18" *)
  wire o7_val_1;
  (* src = "sbox.v:74.12-74.18" *)
  input rand_1;
  wire rand_1;
  (* src = "sbox.v:77.12-77.19" *)
  input rand_10;
  wire rand_10;
  (* src = "sbox.v:71.12-71.19" *)
  input rand_11;
  wire rand_11;
  (* src = "sbox.v:78.12-78.19" *)
  input rand_12;
  wire rand_12;
  (* src = "sbox.v:72.12-72.18" *)
  input rand_2;
  wire rand_2;
  (* src = "sbox.v:69.12-69.18" *)
  input rand_3;
  wire rand_3;
  (* src = "sbox.v:75.12-75.18" *)
  input rand_4;
  wire rand_4;
  (* src = "sbox.v:79.12-79.18" *)
  input rand_5;
  wire rand_5;
  (* src = "sbox.v:68.12-68.18" *)
  input rand_6;
  wire rand_6;
  (* src = "sbox.v:73.12-73.18" *)
  input rand_7;
  wire rand_7;
  (* src = "sbox.v:70.12-70.18" *)
  input rand_8;
  wire rand_8;
  (* src = "sbox.v:76.12-76.18" *)
  input rand_9;
  wire rand_9;
  (* src = "sbox.v:125.10-125.14" *)
  wire t0_0;
  (* src = "sbox.v:165.10-165.14" *)
  wire t2_0;
  (* src = "sbox.v:207.10-207.14" *)
  wire t4_0;
  (* src = "sbox.v:195.9-195.35" *)
  wire temp_hpc2_v_1_order0_HPC24;
  (* src = "sbox.v:235.9-235.35" *)
  wire temp_hpc2_v_1_order0_HPC26;
  (* src = "sbox.v:200.9-200.35" *)
  wire temp_hpc2_v_1_order1_HPC24;
  (* src = "sbox.v:240.9-240.35" *)
  wire temp_hpc2_v_1_order1_HPC26;
  (* src = "sbox.v:214.9-214.45" *)
  wire temp_hpc2sw_v_1_order0_HPC2_swapped5;
  (* src = "sbox.v:252.9-252.45" *)
  wire temp_hpc2sw_v_1_order0_HPC2_swapped7;
  (* src = "sbox.v:219.9-219.45" *)
  wire temp_hpc2sw_v_1_order1_HPC2_swapped5;
  (* src = "sbox.v:257.9-257.45" *)
  wire temp_hpc2sw_v_1_order1_HPC2_swapped7;
  (* src = "sbox.v:109.9-109.35" *)
  wire temp_hpc3_v_1_order0_HPC30;
  (* src = "sbox.v:129.9-129.35" *)
  wire temp_hpc3_v_1_order0_HPC31;
  (* src = "sbox.v:149.9-149.35" *)
  wire temp_hpc3_v_1_order0_HPC32;
  (* src = "sbox.v:175.9-175.35" *)
  wire temp_hpc3_v_1_order0_HPC33;
  (* src = "sbox.v:116.9-116.35" *)
  wire temp_hpc3_v_1_order1_HPC30;
  (* src = "sbox.v:136.9-136.35" *)
  wire temp_hpc3_v_1_order1_HPC31;
  (* src = "sbox.v:156.9-156.35" *)
  wire temp_hpc3_v_1_order1_HPC32;
  (* src = "sbox.v:182.9-182.35" *)
  wire temp_hpc3_v_1_order1_HPC33;
  (* src = "sbox.v:194.10-194.19" *)
  wire u00_HPC24;
  (* src = "sbox.v:206.9-206.22" *)
  wire u00_HPC24_reg;
  (* src = "sbox.v:234.10-234.19" *)
  wire u00_HPC26;
  (* src = "sbox.v:246.9-246.22" *)
  wire u00_HPC26_reg;
  (* src = "sbox.v:213.10-213.27" *)
  wire u00_HPC2_swapped5;
  (* src = "sbox.v:226.9-226.30" *)
  wire u00_HPC2_swapped5_reg;
  (* src = "sbox.v:251.10-251.27" *)
  wire u00_HPC2_swapped7;
  (* src = "sbox.v:264.9-264.30" *)
  wire u00_HPC2_swapped7_reg;
  (* src = "sbox.v:108.10-108.19" *)
  wire u00_HPC30;
  (* src = "sbox.v:124.9-124.22" *)
  wire u00_HPC30_reg;
  (* src = "sbox.v:128.10-128.19" *)
  wire u00_HPC31;
  (* src = "sbox.v:144.9-144.22" *)
  wire u00_HPC31_reg;
  (* src = "sbox.v:148.10-148.19" *)
  wire u00_HPC32;
  (* src = "sbox.v:164.9-164.22" *)
  wire u00_HPC32_reg;
  (* src = "sbox.v:174.10-174.19" *)
  wire u00_HPC33;
  (* src = "sbox.v:190.9-190.22" *)
  wire u00_HPC33_reg;
  (* src = "sbox.v:205.10-205.19" *)
  wire u11_HPC24;
  (* src = "sbox.v:208.9-208.22" *)
  wire u11_HPC24_reg;
  (* src = "sbox.v:245.10-245.19" *)
  wire u11_HPC26;
  (* src = "sbox.v:248.9-248.22" *)
  wire u11_HPC26_reg;
  (* src = "sbox.v:225.10-225.27" *)
  wire u11_HPC2_swapped5;
  (* src = "sbox.v:228.9-228.30" *)
  wire u11_HPC2_swapped5_reg;
  (* src = "sbox.v:263.10-263.27" *)
  wire u11_HPC2_swapped7;
  (* src = "sbox.v:266.9-266.30" *)
  wire u11_HPC2_swapped7_reg;
  (* src = "sbox.v:123.10-123.19" *)
  wire u11_HPC30;
  (* src = "sbox.v:126.9-126.22" *)
  wire u11_HPC30_reg;
  (* src = "sbox.v:143.10-143.19" *)
  wire u11_HPC31;
  (* src = "sbox.v:146.9-146.22" *)
  wire u11_HPC31_reg;
  (* src = "sbox.v:163.10-163.19" *)
  wire u11_HPC32;
  (* src = "sbox.v:166.9-166.22" *)
  wire u11_HPC32_reg;
  (* src = "sbox.v:189.10-189.19" *)
  wire u11_HPC33;
  (* src = "sbox.v:192.9-192.22" *)
  wire u11_HPC33_reg;
  (* src = "sbox.v:196.9-196.18" *)
  wire v01_HPC24;
  (* src = "sbox.v:236.9-236.18" *)
  wire v01_HPC26;
  (* src = "sbox.v:215.9-215.26" *)
  wire v01_HPC2_swapped5;
  (* src = "sbox.v:253.9-253.26" *)
  wire v01_HPC2_swapped7;
  (* src = "sbox.v:201.9-201.18" *)
  wire v10_HPC24;
  (* src = "sbox.v:241.9-241.18" *)
  wire v10_HPC26;
  (* src = "sbox.v:220.9-220.26" *)
  wire v10_HPC2_swapped5;
  (* src = "sbox.v:258.9-258.26" *)
  wire v10_HPC2_swapped7;
  (* src = "sbox.v:198.9-198.18" *)
  wire w01_HPC24;
  (* src = "sbox.v:238.9-238.18" *)
  wire w01_HPC26;
  (* src = "sbox.v:217.9-217.26" *)
  wire w01_HPC2_swapped5;
  (* src = "sbox.v:255.9-255.26" *)
  wire w01_HPC2_swapped7;
  (* src = "sbox.v:114.9-114.18" *)
  wire w01_HPC30;
  (* src = "sbox.v:134.9-134.18" *)
  wire w01_HPC31;
  (* src = "sbox.v:154.9-154.18" *)
  wire w01_HPC32;
  (* src = "sbox.v:180.9-180.18" *)
  wire w01_HPC33;
  (* src = "sbox.v:203.9-203.18" *)
  wire w10_HPC24;
  (* src = "sbox.v:243.9-243.18" *)
  wire w10_HPC26;
  (* src = "sbox.v:222.9-222.26" *)
  wire w10_HPC2_swapped5;
  (* src = "sbox.v:260.9-260.26" *)
  wire w10_HPC2_swapped7;
  (* src = "sbox.v:121.9-121.18" *)
  wire w10_HPC30;
  (* src = "sbox.v:141.9-141.18" *)
  wire w10_HPC31;
  (* src = "sbox.v:161.9-161.18" *)
  wire w10_HPC32;
  (* src = "sbox.v:187.9-187.18" *)
  wire w10_HPC33;
  (* src = "sbox.v:284.10-284.23" *)
  wire z673_assgn673;
  (* src = "sbox.v:285.9-285.23" *)
  wire z673_assgn6730;
  (* src = "sbox.v:286.9-286.23" *)
  wire z673_assgn6731;
  (* src = "sbox.v:287.10-287.23" *)
  wire z675_assgn675;
  (* src = "sbox.v:288.9-288.23" *)
  wire z675_assgn6750;
  (* src = "sbox.v:289.9-289.23" *)
  wire z675_assgn6751;
  (* src = "sbox.v:290.10-290.23" *)
  wire z677_assgn677;
  (* src = "sbox.v:291.9-291.23" *)
  wire z677_assgn6770;
  (* src = "sbox.v:292.10-292.23" *)
  wire z679_assgn679;
  (* src = "sbox.v:293.9-293.23" *)
  wire z679_assgn6790;
  (* src = "sbox.v:294.10-294.23" *)
  wire z685_assgn685;
  (* src = "sbox.v:295.9-295.23" *)
  wire z685_assgn6850;
  (* src = "sbox.v:296.9-296.23" *)
  wire z685_assgn6851;
  (* src = "sbox.v:297.10-297.23" *)
  wire z687_assgn687;
  (* src = "sbox.v:298.9-298.23" *)
  wire z687_assgn6870;
  (* src = "sbox.v:299.9-299.23" *)
  wire z687_assgn6871;
  (* src = "sbox.v:300.10-300.23" *)
  wire z689_assgn689;
  (* src = "sbox.v:301.9-301.23" *)
  wire z689_assgn6890;
  (* src = "sbox.v:302.9-302.23" *)
  wire z689_assgn6891;
  (* src = "sbox.v:303.10-303.23" *)
  wire z691_assgn691;
  (* src = "sbox.v:304.9-304.23" *)
  wire z691_assgn6910;
  (* src = "sbox.v:305.9-305.23" *)
  wire z691_assgn6911;
  (* src = "sbox.v:306.10-306.23" *)
  wire z693_assgn693;
  (* src = "sbox.v:307.9-307.23" *)
  wire z693_assgn6930;
  (* src = "sbox.v:308.10-308.23" *)
  wire z695_assgn695;
  (* src = "sbox.v:309.9-309.23" *)
  wire z695_assgn6950;
  INV_X1 _195_ (
    .A(i2_1),
    .ZN(n2_1)
  );
  INV_X1 _196_ (
    .A(i3_1),
    .ZN(n3_1)
  );
  INV_X1 _197_ (
    .A(i6_1),
    .ZN(n6_1)
  );
  INV_X1 _198_ (
    .A(i6_0),
    .ZN(_040_)
  );
  INV_X1 _199_ (
    .A(i3_0),
    .ZN(_041_)
  );
  INV_X1 _200_ (
    .A(i2_0),
    .ZN(_042_)
  );
  INV_X1 _201_ (
    .A(n3_1_reg),
    .ZN(_043_)
  );
  INV_X1 _202_ (
    .A(rand_7),
    .ZN(_044_)
  );
  INV_X1 _203_ (
    .A(rand_9),
    .ZN(_045_)
  );
  INV_X1 _204_ (
    .A(temp_hpc2_v_1_order1_HPC24),
    .ZN(_046_)
  );
  INV_X1 _205_ (
    .A(rand_10),
    .ZN(_047_)
  );
  INV_X1 _206_ (
    .A(rand_11),
    .ZN(_048_)
  );
  INV_X1 _207_ (
    .A(rand_12),
    .ZN(_049_)
  );
  NAND2_X1 _208_ (
    .A1(temp_hpc3_v_1_order1_HPC30),
    .A2(n6_1_reg),
    .ZN(_050_)
  );
  XOR2_X1 _209_ (
    .A(w10_HPC30),
    .B(_050_),
    .Z(_051_)
  );
  XNOR2_X1 _210_ (
    .A(u11_HPC30_reg),
    .B(_051_),
    .ZN(_052_)
  );
  INV_X1 _211_ (
    .A(_052_),
    .ZN(nt0_1)
  );
  NAND2_X1 _212_ (
    .A1(temp_hpc3_v_1_order1_HPC32),
    .A2(n2_1_reg),
    .ZN(_053_)
  );
  XOR2_X1 _213_ (
    .A(w10_HPC32),
    .B(_053_),
    .Z(_054_)
  );
  XNOR2_X1 _214_ (
    .A(u11_HPC32_reg),
    .B(_054_),
    .ZN(_055_)
  );
  INV_X1 _215_ (
    .A(_055_),
    .ZN(nt2_1)
  );
  NAND2_X1 _216_ (
    .A1(temp_hpc3_v_1_order0_HPC30),
    .A2(n6_0_reg),
    .ZN(_056_)
  );
  XOR2_X1 _217_ (
    .A(w01_HPC30),
    .B(_056_),
    .Z(_057_)
  );
  XNOR2_X1 _218_ (
    .A(u00_HPC30_reg),
    .B(_057_),
    .ZN(nt0_0)
  );
  XNOR2_X1 _219_ (
    .A(v10_HPC24),
    .B(w10_HPC24),
    .ZN(_058_)
  );
  XNOR2_X1 _220_ (
    .A(u11_HPC24_reg),
    .B(_058_),
    .ZN(_059_)
  );
  INV_X1 _221_ (
    .A(_059_),
    .ZN(nt4_1)
  );
  AND2_X1 _222_ (
    .A1(i6_0),
    .A2(i7_0),
    .ZN(u00_HPC30)
  );
  NOR2_X1 _223_ (
    .A1(i6_1),
    .A2(i7_1),
    .ZN(u11_HPC30)
  );
  NOR2_X1 _224_ (
    .A1(_041_),
    .A2(_042_),
    .ZN(u00_HPC31)
  );
  NOR2_X1 _225_ (
    .A1(i2_1),
    .A2(i3_1),
    .ZN(u11_HPC31)
  );
  AND2_X1 _226_ (
    .A1(i2_0),
    .A2(i1_0),
    .ZN(u00_HPC32)
  );
  NOR2_X1 _227_ (
    .A1(i1_1),
    .A2(i2_1),
    .ZN(u11_HPC32)
  );
  NAND2_X1 _228_ (
    .A1(temp_hpc3_v_1_order0_HPC32),
    .A2(n2_0_reg),
    .ZN(_060_)
  );
  XOR2_X1 _229_ (
    .A(w01_HPC32),
    .B(_060_),
    .Z(_061_)
  );
  XNOR2_X1 _230_ (
    .A(u00_HPC32_reg),
    .B(_061_),
    .ZN(nt2_0)
  );
  NAND2_X1 _231_ (
    .A1(temp_hpc3_v_1_order0_HPC31),
    .A2(n3_0_reg),
    .ZN(_062_)
  );
  XOR2_X1 _232_ (
    .A(w01_HPC31),
    .B(_062_),
    .Z(_063_)
  );
  XNOR2_X1 _233_ (
    .A(u00_HPC31_reg),
    .B(_063_),
    .ZN(_064_)
  );
  AND2_X1 _234_ (
    .A1(nt0_0),
    .A2(_064_),
    .ZN(u00_HPC33)
  );
  NAND2_X1 _235_ (
    .A1(temp_hpc3_v_1_order1_HPC31),
    .A2(n3_1_reg),
    .ZN(_065_)
  );
  XOR2_X1 _236_ (
    .A(w10_HPC31),
    .B(_065_),
    .Z(_066_)
  );
  XNOR2_X1 _237_ (
    .A(u11_HPC31_reg),
    .B(_066_),
    .ZN(_067_)
  );
  NOR2_X1 _238_ (
    .A1(_052_),
    .A2(_067_),
    .ZN(u11_HPC33)
  );
  AND2_X1 _239_ (
    .A1(n3_0_reg),
    .A2(_064_),
    .ZN(u00_HPC24)
  );
  NOR2_X1 _240_ (
    .A1(_043_),
    .A2(_067_),
    .ZN(u11_HPC24)
  );
  XNOR2_X1 _241_ (
    .A(v01_HPC24),
    .B(w01_HPC24),
    .ZN(_068_)
  );
  XNOR2_X1 _242_ (
    .A(u00_HPC24_reg),
    .B(_068_),
    .ZN(nt4_0)
  );
  NAND2_X1 _243_ (
    .A1(temp_hpc3_v_1_order0_HPC33),
    .A2(nt0_0_reg),
    .ZN(_069_)
  );
  XOR2_X1 _244_ (
    .A(w01_HPC33),
    .B(_069_),
    .Z(_070_)
  );
  XNOR2_X1 _245_ (
    .A(u00_HPC33_reg),
    .B(_070_),
    .ZN(_071_)
  );
  AND2_X1 _246_ (
    .A1(nt2_0_reg),
    .A2(_071_),
    .ZN(u00_HPC2_swapped5)
  );
  NAND2_X1 _247_ (
    .A1(temp_hpc3_v_1_order1_HPC33),
    .A2(nt0_1_reg),
    .ZN(_072_)
  );
  XNOR2_X1 _248_ (
    .A(w10_HPC33),
    .B(_072_),
    .ZN(_073_)
  );
  XNOR2_X1 _249_ (
    .A(u11_HPC33_reg),
    .B(_073_),
    .ZN(_074_)
  );
  AND2_X1 _250_ (
    .A1(nt2_1_reg),
    .A2(_074_),
    .ZN(u11_HPC2_swapped5)
  );
  AND2_X1 _251_ (
    .A1(nt0_0_reg),
    .A2(_071_),
    .ZN(u00_HPC26)
  );
  AND2_X1 _252_ (
    .A1(nt0_1_reg),
    .A2(_074_),
    .ZN(u11_HPC26)
  );
  XNOR2_X1 _253_ (
    .A(v01_HPC2_swapped5),
    .B(w01_HPC2_swapped5),
    .ZN(_075_)
  );
  XNOR2_X1 _254_ (
    .A(u00_HPC2_swapped5_reg),
    .B(_075_),
    .ZN(_076_)
  );
  AND2_X1 _255_ (
    .A1(nt4_0_reg),
    .A2(_076_),
    .ZN(u00_HPC2_swapped7)
  );
  XOR2_X1 _256_ (
    .A(v10_HPC2_swapped5),
    .B(w10_HPC2_swapped5),
    .Z(_077_)
  );
  XNOR2_X1 _257_ (
    .A(u11_HPC2_swapped5_reg),
    .B(_077_),
    .ZN(_078_)
  );
  AND2_X1 _258_ (
    .A1(nt4_1_reg),
    .A2(_078_),
    .ZN(u11_HPC2_swapped7)
  );
  XOR2_X1 _259_ (
    .A(i4_0),
    .B(nt0_0),
    .Z(o6_val_0)
  );
  XOR2_X1 _260_ (
    .A(i4_1),
    .B(_052_),
    .Z(o6_val_1)
  );
  XOR2_X1 _261_ (
    .A(i0_0),
    .B(_064_),
    .Z(o5_val_0)
  );
  XOR2_X1 _262_ (
    .A(i0_1),
    .B(_067_),
    .Z(o5_val_1)
  );
  XNOR2_X1 _263_ (
    .A(_040_),
    .B(nt2_0),
    .ZN(o2_val_0)
  );
  XNOR2_X1 _264_ (
    .A(n6_1),
    .B(_055_),
    .ZN(o2_val_1)
  );
  XOR2_X1 _265_ (
    .A(i5_0),
    .B(_071_),
    .Z(o7_val_0)
  );
  XNOR2_X1 _266_ (
    .A(i5_1),
    .B(_074_),
    .ZN(o7_val_1)
  );
  XOR2_X1 _267_ (
    .A(v01_HPC2_swapped7),
    .B(w01_HPC2_swapped7),
    .Z(_079_)
  );
  XNOR2_X1 _268_ (
    .A(u00_HPC2_swapped7_reg),
    .B(_079_),
    .ZN(_080_)
  );
  XNOR2_X1 _269_ (
    .A(i2_0),
    .B(_080_),
    .ZN(o0_val_0)
  );
  XOR2_X1 _270_ (
    .A(v10_HPC2_swapped7),
    .B(w10_HPC2_swapped7),
    .Z(_081_)
  );
  XNOR2_X1 _271_ (
    .A(u11_HPC2_swapped7_reg),
    .B(_081_),
    .ZN(_082_)
  );
  XNOR2_X1 _272_ (
    .A(i2_1),
    .B(_082_),
    .ZN(o0_val_1)
  );
  XOR2_X1 _273_ (
    .A(v01_HPC26),
    .B(w01_HPC26),
    .Z(_083_)
  );
  XNOR2_X1 _274_ (
    .A(u00_HPC26_reg),
    .B(_083_),
    .ZN(_084_)
  );
  XNOR2_X1 _275_ (
    .A(i3_0),
    .B(_084_),
    .ZN(o4_val_0)
  );
  XOR2_X1 _276_ (
    .A(v10_HPC26),
    .B(w10_HPC26),
    .Z(_085_)
  );
  XNOR2_X1 _277_ (
    .A(u11_HPC26_reg),
    .B(_085_),
    .ZN(_086_)
  );
  XNOR2_X1 _278_ (
    .A(i3_1),
    .B(_086_),
    .ZN(o4_val_1)
  );
  XOR2_X1 _279_ (
    .A(i7_0),
    .B(_076_),
    .Z(o1_val_0)
  );
  XNOR2_X1 _280_ (
    .A(i7_1),
    .B(_078_),
    .ZN(o1_val_1)
  );
  XOR2_X1 _281_ (
    .A(i1_0),
    .B(nt4_0),
    .Z(o3_val_0)
  );
  XOR2_X1 _282_ (
    .A(i1_1),
    .B(_059_),
    .Z(o3_val_1)
  );
  XNOR2_X1 _283_ (
    .A(i7_1),
    .B(rand_1),
    .ZN(_008_)
  );
  NAND2_X1 _284_ (
    .A1(_040_),
    .A2(rand_1),
    .ZN(_087_)
  );
  XNOR2_X1 _285_ (
    .A(rand_2),
    .B(_087_),
    .ZN(_028_)
  );
  XOR2_X1 _286_ (
    .A(i7_0),
    .B(rand_1),
    .Z(_012_)
  );
  NAND2_X1 _287_ (
    .A1(i6_1),
    .A2(rand_1),
    .ZN(_088_)
  );
  XNOR2_X1 _288_ (
    .A(rand_2),
    .B(_088_),
    .ZN(_036_)
  );
  XNOR2_X1 _289_ (
    .A(i2_1),
    .B(rand_3),
    .ZN(_009_)
  );
  NAND2_X1 _290_ (
    .A1(_041_),
    .A2(rand_3),
    .ZN(_089_)
  );
  XNOR2_X1 _291_ (
    .A(rand_4),
    .B(_089_),
    .ZN(_029_)
  );
  XOR2_X1 _292_ (
    .A(i2_0),
    .B(rand_3),
    .Z(_013_)
  );
  NAND2_X1 _293_ (
    .A1(i3_1),
    .A2(rand_3),
    .ZN(_090_)
  );
  XNOR2_X1 _294_ (
    .A(rand_4),
    .B(_090_),
    .ZN(_037_)
  );
  XNOR2_X1 _295_ (
    .A(i1_1),
    .B(rand_5),
    .ZN(_010_)
  );
  NAND2_X1 _296_ (
    .A1(_042_),
    .A2(rand_5),
    .ZN(_091_)
  );
  XNOR2_X1 _297_ (
    .A(rand_6),
    .B(_091_),
    .ZN(_030_)
  );
  XOR2_X1 _298_ (
    .A(i1_0),
    .B(rand_5),
    .Z(_014_)
  );
  NAND2_X1 _299_ (
    .A1(i2_1),
    .A2(rand_5),
    .ZN(_092_)
  );
  XNOR2_X1 _300_ (
    .A(rand_6),
    .B(_092_),
    .ZN(_038_)
  );
  XNOR2_X1 _301_ (
    .A(rand_7),
    .B(_067_),
    .ZN(_011_)
  );
  NOR2_X1 _302_ (
    .A1(_044_),
    .A2(nt0_0),
    .ZN(_093_)
  );
  XOR2_X1 _303_ (
    .A(rand_8),
    .B(_093_),
    .Z(_031_)
  );
  XNOR2_X1 _304_ (
    .A(_044_),
    .B(_064_),
    .ZN(_015_)
  );
  NAND2_X1 _305_ (
    .A1(rand_7),
    .A2(_052_),
    .ZN(_094_)
  );
  XNOR2_X1 _306_ (
    .A(rand_8),
    .B(_094_),
    .ZN(_039_)
  );
  XNOR2_X1 _307_ (
    .A(i3_1),
    .B(rand_9),
    .ZN(_000_)
  );
  AND2_X1 _308_ (
    .A1(temp_hpc2_v_1_order0_HPC24),
    .A2(_064_),
    .ZN(_016_)
  );
  NOR2_X1 _309_ (
    .A1(_045_),
    .A2(_064_),
    .ZN(_024_)
  );
  XOR2_X1 _310_ (
    .A(i3_0),
    .B(rand_9),
    .Z(_002_)
  );
  NOR2_X1 _311_ (
    .A1(_046_),
    .A2(_067_),
    .ZN(_020_)
  );
  AND2_X1 _312_ (
    .A1(rand_9),
    .A2(_067_),
    .ZN(_032_)
  );
  XNOR2_X1 _313_ (
    .A(rand_10),
    .B(_055_),
    .ZN(_004_)
  );
  AND2_X1 _314_ (
    .A1(temp_hpc2sw_v_1_order0_HPC2_swapped5),
    .A2(_071_),
    .ZN(_018_)
  );
  NOR2_X1 _315_ (
    .A1(_047_),
    .A2(_071_),
    .ZN(_026_)
  );
  XNOR2_X1 _316_ (
    .A(_047_),
    .B(nt2_0),
    .ZN(_006_)
  );
  AND2_X1 _317_ (
    .A1(temp_hpc2sw_v_1_order1_HPC2_swapped5),
    .A2(_074_),
    .ZN(_022_)
  );
  NOR2_X1 _318_ (
    .A1(_047_),
    .A2(_074_),
    .ZN(_034_)
  );
  XNOR2_X1 _319_ (
    .A(rand_11),
    .B(_052_),
    .ZN(_001_)
  );
  AND2_X1 _320_ (
    .A1(temp_hpc2_v_1_order0_HPC26),
    .A2(_071_),
    .ZN(_017_)
  );
  NOR2_X1 _321_ (
    .A1(_048_),
    .A2(_071_),
    .ZN(_025_)
  );
  XNOR2_X1 _322_ (
    .A(_048_),
    .B(nt0_0),
    .ZN(_003_)
  );
  AND2_X1 _323_ (
    .A1(temp_hpc2_v_1_order1_HPC26),
    .A2(_074_),
    .ZN(_021_)
  );
  NOR2_X1 _324_ (
    .A1(_048_),
    .A2(_074_),
    .ZN(_033_)
  );
  XNOR2_X1 _325_ (
    .A(rand_12),
    .B(_059_),
    .ZN(_005_)
  );
  AND2_X1 _326_ (
    .A1(temp_hpc2sw_v_1_order0_HPC2_swapped7),
    .A2(_076_),
    .ZN(_019_)
  );
  NOR2_X1 _327_ (
    .A1(_049_),
    .A2(_076_),
    .ZN(_027_)
  );
  XNOR2_X1 _328_ (
    .A(_049_),
    .B(nt4_0),
    .ZN(_007_)
  );
  AND2_X1 _329_ (
    .A1(temp_hpc2sw_v_1_order1_HPC2_swapped7),
    .A2(_078_),
    .ZN(_023_)
  );
  NOR2_X1 _330_ (
    .A1(_049_),
    .A2(_078_),
    .ZN(_035_)
  );
  (* src = "sbox.v:440.5-541.8" *)
  DFF_X1 _331_ (
    .CK(clk),
    .D(o0_val_0),
    .Q(o0_0),
    .QN(_096_)
  );
  (* src = "sbox.v:440.5-541.8" *)
  DFF_X1 _332_ (
    .CK(clk),
    .D(o0_val_1),
    .Q(o0_1),
    .QN(_097_)
  );
  (* src = "sbox.v:440.5-541.8" *)
  DFF_X1 _333_ (
    .CK(clk),
    .D(o1_val_0),
    .Q(o1_0),
    .QN(_098_)
  );
  (* src = "sbox.v:440.5-541.8" *)
  DFF_X1 _334_ (
    .CK(clk),
    .D(o1_val_1),
    .Q(o1_1),
    .QN(_099_)
  );
  (* src = "sbox.v:440.5-541.8" *)
  DFF_X1 _335_ (
    .CK(clk),
    .D(z673_assgn6731),
    .Q(o2_0),
    .QN(_100_)
  );
  (* src = "sbox.v:440.5-541.8" *)
  DFF_X1 _336_ (
    .CK(clk),
    .D(z675_assgn6751),
    .Q(o2_1),
    .QN(_101_)
  );
  (* src = "sbox.v:440.5-541.8" *)
  DFF_X1 _337_ (
    .CK(clk),
    .D(z677_assgn6770),
    .Q(o3_0),
    .QN(_102_)
  );
  (* src = "sbox.v:440.5-541.8" *)
  DFF_X1 _338_ (
    .CK(clk),
    .D(z679_assgn6790),
    .Q(o3_1),
    .QN(_103_)
  );
  (* src = "sbox.v:440.5-541.8" *)
  DFF_X1 _339_ (
    .CK(clk),
    .D(o4_val_0),
    .Q(o4_0),
    .QN(_104_)
  );
  (* src = "sbox.v:440.5-541.8" *)
  DFF_X1 _340_ (
    .CK(clk),
    .D(o4_val_1),
    .Q(o4_1),
    .QN(_105_)
  );
  (* src = "sbox.v:440.5-541.8" *)
  DFF_X1 _341_ (
    .CK(clk),
    .D(z685_assgn6851),
    .Q(o5_0),
    .QN(_106_)
  );
  (* src = "sbox.v:440.5-541.8" *)
  DFF_X1 _342_ (
    .CK(clk),
    .D(z687_assgn6871),
    .Q(o5_1),
    .QN(_107_)
  );
  (* src = "sbox.v:440.5-541.8" *)
  DFF_X1 _343_ (
    .CK(clk),
    .D(z689_assgn6891),
    .Q(o6_0),
    .QN(_108_)
  );
  (* src = "sbox.v:440.5-541.8" *)
  DFF_X1 _344_ (
    .CK(clk),
    .D(z691_assgn6911),
    .Q(o6_1),
    .QN(_109_)
  );
  (* src = "sbox.v:440.5-541.8" *)
  DFF_X1 _345_ (
    .CK(clk),
    .D(z693_assgn6930),
    .Q(o7_0),
    .QN(_110_)
  );
  (* src = "sbox.v:440.5-541.8" *)
  DFF_X1 _346_ (
    .CK(clk),
    .D(z695_assgn6950),
    .Q(o7_1),
    .QN(_111_)
  );
  (* src = "sbox.v:440.5-541.8" *)
  DFF_X1 _347_ (
    .CK(clk),
    .D(_008_),
    .Q(temp_hpc3_v_1_order0_HPC30),
    .QN(_112_)
  );
  (* src = "sbox.v:440.5-541.8" *)
  DFF_X1 _348_ (
    .CK(clk),
    .D(i6_0),
    .Q(n6_0_reg),
    .QN(_113_)
  );
  (* src = "sbox.v:440.5-541.8" *)
  DFF_X1 _349_ (
    .CK(clk),
    .D(_028_),
    .Q(w01_HPC30),
    .QN(_114_)
  );
  (* src = "sbox.v:440.5-541.8" *)
  DFF_X1 _350_ (
    .CK(clk),
    .D(_012_),
    .Q(temp_hpc3_v_1_order1_HPC30),
    .QN(_115_)
  );
  (* src = "sbox.v:440.5-541.8" *)
  DFF_X1 _351_ (
    .CK(clk),
    .D(n6_1),
    .Q(n6_1_reg),
    .QN(_116_)
  );
  (* src = "sbox.v:440.5-541.8" *)
  DFF_X1 _352_ (
    .CK(clk),
    .D(_036_),
    .Q(w10_HPC30),
    .QN(_117_)
  );
  (* src = "sbox.v:440.5-541.8" *)
  DFF_X1 _353_ (
    .CK(clk),
    .D(u00_HPC30),
    .Q(u00_HPC30_reg),
    .QN(_118_)
  );
  (* src = "sbox.v:440.5-541.8" *)
  DFF_X1 _354_ (
    .CK(clk),
    .D(u11_HPC30),
    .Q(u11_HPC30_reg),
    .QN(_119_)
  );
  (* src = "sbox.v:440.5-541.8" *)
  DFF_X1 _355_ (
    .CK(clk),
    .D(_009_),
    .Q(temp_hpc3_v_1_order0_HPC31),
    .QN(_120_)
  );
  (* src = "sbox.v:440.5-541.8" *)
  DFF_X1 _356_ (
    .CK(clk),
    .D(i3_0),
    .Q(n3_0_reg),
    .QN(_121_)
  );
  (* src = "sbox.v:440.5-541.8" *)
  DFF_X1 _357_ (
    .CK(clk),
    .D(_029_),
    .Q(w01_HPC31),
    .QN(_122_)
  );
  (* src = "sbox.v:440.5-541.8" *)
  DFF_X1 _358_ (
    .CK(clk),
    .D(_013_),
    .Q(temp_hpc3_v_1_order1_HPC31),
    .QN(_123_)
  );
  (* src = "sbox.v:440.5-541.8" *)
  DFF_X1 _359_ (
    .CK(clk),
    .D(n3_1),
    .Q(n3_1_reg),
    .QN(_124_)
  );
  (* src = "sbox.v:440.5-541.8" *)
  DFF_X1 _360_ (
    .CK(clk),
    .D(_037_),
    .Q(w10_HPC31),
    .QN(_125_)
  );
  (* src = "sbox.v:440.5-541.8" *)
  DFF_X1 _361_ (
    .CK(clk),
    .D(u00_HPC31),
    .Q(u00_HPC31_reg),
    .QN(_126_)
  );
  (* src = "sbox.v:440.5-541.8" *)
  DFF_X1 _362_ (
    .CK(clk),
    .D(u11_HPC31),
    .Q(u11_HPC31_reg),
    .QN(_127_)
  );
  (* src = "sbox.v:440.5-541.8" *)
  DFF_X1 _363_ (
    .CK(clk),
    .D(_010_),
    .Q(temp_hpc3_v_1_order0_HPC32),
    .QN(_128_)
  );
  (* src = "sbox.v:440.5-541.8" *)
  DFF_X1 _364_ (
    .CK(clk),
    .D(i2_0),
    .Q(n2_0_reg),
    .QN(_129_)
  );
  (* src = "sbox.v:440.5-541.8" *)
  DFF_X1 _365_ (
    .CK(clk),
    .D(_030_),
    .Q(w01_HPC32),
    .QN(_130_)
  );
  (* src = "sbox.v:440.5-541.8" *)
  DFF_X1 _366_ (
    .CK(clk),
    .D(_014_),
    .Q(temp_hpc3_v_1_order1_HPC32),
    .QN(_131_)
  );
  (* src = "sbox.v:440.5-541.8" *)
  DFF_X1 _367_ (
    .CK(clk),
    .D(n2_1),
    .Q(n2_1_reg),
    .QN(_132_)
  );
  (* src = "sbox.v:440.5-541.8" *)
  DFF_X1 _368_ (
    .CK(clk),
    .D(_038_),
    .Q(w10_HPC32),
    .QN(_133_)
  );
  (* src = "sbox.v:440.5-541.8" *)
  DFF_X1 _369_ (
    .CK(clk),
    .D(u00_HPC32),
    .Q(u00_HPC32_reg),
    .QN(_134_)
  );
  (* src = "sbox.v:440.5-541.8" *)
  DFF_X1 _370_ (
    .CK(clk),
    .D(u11_HPC32),
    .Q(u11_HPC32_reg),
    .QN(_135_)
  );
  (* src = "sbox.v:440.5-541.8" *)
  DFF_X1 _371_ (
    .CK(clk),
    .D(_011_),
    .Q(temp_hpc3_v_1_order0_HPC33),
    .QN(_136_)
  );
  (* src = "sbox.v:440.5-541.8" *)
  DFF_X1 _372_ (
    .CK(clk),
    .D(nt0_0),
    .Q(nt0_0_reg),
    .QN(_137_)
  );
  (* src = "sbox.v:440.5-541.8" *)
  DFF_X1 _373_ (
    .CK(clk),
    .D(_031_),
    .Q(w01_HPC33),
    .QN(_138_)
  );
  (* src = "sbox.v:440.5-541.8" *)
  DFF_X1 _374_ (
    .CK(clk),
    .D(_015_),
    .Q(temp_hpc3_v_1_order1_HPC33),
    .QN(_139_)
  );
  (* src = "sbox.v:440.5-541.8" *)
  DFF_X1 _375_ (
    .CK(clk),
    .D(nt0_1),
    .Q(nt0_1_reg),
    .QN(_140_)
  );
  (* src = "sbox.v:440.5-541.8" *)
  DFF_X1 _376_ (
    .CK(clk),
    .D(_039_),
    .Q(w10_HPC33),
    .QN(_141_)
  );
  (* src = "sbox.v:440.5-541.8" *)
  DFF_X1 _377_ (
    .CK(clk),
    .D(u00_HPC33),
    .Q(u00_HPC33_reg),
    .QN(_142_)
  );
  (* src = "sbox.v:440.5-541.8" *)
  DFF_X1 _378_ (
    .CK(clk),
    .D(u11_HPC33),
    .Q(u11_HPC33_reg),
    .QN(_143_)
  );
  (* src = "sbox.v:440.5-541.8" *)
  DFF_X1 _379_ (
    .CK(clk),
    .D(_000_),
    .Q(temp_hpc2_v_1_order0_HPC24),
    .QN(_144_)
  );
  (* src = "sbox.v:440.5-541.8" *)
  DFF_X1 _380_ (
    .CK(clk),
    .D(_016_),
    .Q(v01_HPC24),
    .QN(_145_)
  );
  (* src = "sbox.v:440.5-541.8" *)
  DFF_X1 _381_ (
    .CK(clk),
    .D(_024_),
    .Q(w01_HPC24),
    .QN(_146_)
  );
  (* src = "sbox.v:440.5-541.8" *)
  DFF_X1 _382_ (
    .CK(clk),
    .D(_002_),
    .Q(temp_hpc2_v_1_order1_HPC24),
    .QN(_147_)
  );
  (* src = "sbox.v:440.5-541.8" *)
  DFF_X1 _383_ (
    .CK(clk),
    .D(_020_),
    .Q(v10_HPC24),
    .QN(_148_)
  );
  (* src = "sbox.v:440.5-541.8" *)
  DFF_X1 _384_ (
    .CK(clk),
    .D(_032_),
    .Q(w10_HPC24),
    .QN(_149_)
  );
  (* src = "sbox.v:440.5-541.8" *)
  DFF_X1 _385_ (
    .CK(clk),
    .D(u00_HPC24),
    .Q(u00_HPC24_reg),
    .QN(_150_)
  );
  (* src = "sbox.v:440.5-541.8" *)
  DFF_X1 _386_ (
    .CK(clk),
    .D(u11_HPC24),
    .Q(u11_HPC24_reg),
    .QN(_151_)
  );
  (* src = "sbox.v:440.5-541.8" *)
  DFF_X1 _387_ (
    .CK(clk),
    .D(nt2_0),
    .Q(nt2_0_reg),
    .QN(_152_)
  );
  (* src = "sbox.v:440.5-541.8" *)
  DFF_X1 _388_ (
    .CK(clk),
    .D(_004_),
    .Q(temp_hpc2sw_v_1_order0_HPC2_swapped5),
    .QN(_153_)
  );
  (* src = "sbox.v:440.5-541.8" *)
  DFF_X1 _389_ (
    .CK(clk),
    .D(_018_),
    .Q(v01_HPC2_swapped5),
    .QN(_154_)
  );
  (* src = "sbox.v:440.5-541.8" *)
  DFF_X1 _390_ (
    .CK(clk),
    .D(_026_),
    .Q(w01_HPC2_swapped5),
    .QN(_155_)
  );
  (* src = "sbox.v:440.5-541.8" *)
  DFF_X1 _391_ (
    .CK(clk),
    .D(_006_),
    .Q(temp_hpc2sw_v_1_order1_HPC2_swapped5),
    .QN(_156_)
  );
  (* src = "sbox.v:440.5-541.8" *)
  DFF_X1 _392_ (
    .CK(clk),
    .D(_022_),
    .Q(v10_HPC2_swapped5),
    .QN(_157_)
  );
  (* src = "sbox.v:440.5-541.8" *)
  DFF_X1 _393_ (
    .CK(clk),
    .D(_034_),
    .Q(w10_HPC2_swapped5),
    .QN(_158_)
  );
  (* src = "sbox.v:440.5-541.8" *)
  DFF_X1 _394_ (
    .CK(clk),
    .D(nt2_1),
    .Q(nt2_1_reg),
    .QN(_159_)
  );
  (* src = "sbox.v:440.5-541.8" *)
  DFF_X1 _395_ (
    .CK(clk),
    .D(u00_HPC2_swapped5),
    .Q(u00_HPC2_swapped5_reg),
    .QN(_160_)
  );
  (* src = "sbox.v:440.5-541.8" *)
  DFF_X1 _396_ (
    .CK(clk),
    .D(u11_HPC2_swapped5),
    .Q(u11_HPC2_swapped5_reg),
    .QN(_161_)
  );
  (* src = "sbox.v:440.5-541.8" *)
  DFF_X1 _397_ (
    .CK(clk),
    .D(_001_),
    .Q(temp_hpc2_v_1_order0_HPC26),
    .QN(_162_)
  );
  (* src = "sbox.v:440.5-541.8" *)
  DFF_X1 _398_ (
    .CK(clk),
    .D(_017_),
    .Q(v01_HPC26),
    .QN(_163_)
  );
  (* src = "sbox.v:440.5-541.8" *)
  DFF_X1 _399_ (
    .CK(clk),
    .D(_025_),
    .Q(w01_HPC26),
    .QN(_164_)
  );
  (* src = "sbox.v:440.5-541.8" *)
  DFF_X1 _400_ (
    .CK(clk),
    .D(_003_),
    .Q(temp_hpc2_v_1_order1_HPC26),
    .QN(_165_)
  );
  (* src = "sbox.v:440.5-541.8" *)
  DFF_X1 _401_ (
    .CK(clk),
    .D(_021_),
    .Q(v10_HPC26),
    .QN(_166_)
  );
  (* src = "sbox.v:440.5-541.8" *)
  DFF_X1 _402_ (
    .CK(clk),
    .D(_033_),
    .Q(w10_HPC26),
    .QN(_167_)
  );
  (* src = "sbox.v:440.5-541.8" *)
  DFF_X1 _403_ (
    .CK(clk),
    .D(u00_HPC26),
    .Q(u00_HPC26_reg),
    .QN(_168_)
  );
  (* src = "sbox.v:440.5-541.8" *)
  DFF_X1 _404_ (
    .CK(clk),
    .D(u11_HPC26),
    .Q(u11_HPC26_reg),
    .QN(_169_)
  );
  (* src = "sbox.v:440.5-541.8" *)
  DFF_X1 _405_ (
    .CK(clk),
    .D(nt4_0),
    .Q(nt4_0_reg),
    .QN(_170_)
  );
  (* src = "sbox.v:440.5-541.8" *)
  DFF_X1 _406_ (
    .CK(clk),
    .D(_005_),
    .Q(temp_hpc2sw_v_1_order0_HPC2_swapped7),
    .QN(_171_)
  );
  (* src = "sbox.v:440.5-541.8" *)
  DFF_X1 _407_ (
    .CK(clk),
    .D(_019_),
    .Q(v01_HPC2_swapped7),
    .QN(_172_)
  );
  (* src = "sbox.v:440.5-541.8" *)
  DFF_X1 _408_ (
    .CK(clk),
    .D(_027_),
    .Q(w01_HPC2_swapped7),
    .QN(_173_)
  );
  (* src = "sbox.v:440.5-541.8" *)
  DFF_X1 _409_ (
    .CK(clk),
    .D(_007_),
    .Q(temp_hpc2sw_v_1_order1_HPC2_swapped7),
    .QN(_174_)
  );
  (* src = "sbox.v:440.5-541.8" *)
  DFF_X1 _410_ (
    .CK(clk),
    .D(_023_),
    .Q(v10_HPC2_swapped7),
    .QN(_175_)
  );
  (* src = "sbox.v:440.5-541.8" *)
  DFF_X1 _411_ (
    .CK(clk),
    .D(_035_),
    .Q(w10_HPC2_swapped7),
    .QN(_176_)
  );
  (* src = "sbox.v:440.5-541.8" *)
  DFF_X1 _412_ (
    .CK(clk),
    .D(nt4_1),
    .Q(nt4_1_reg),
    .QN(_177_)
  );
  (* src = "sbox.v:440.5-541.8" *)
  DFF_X1 _413_ (
    .CK(clk),
    .D(u00_HPC2_swapped7),
    .Q(u00_HPC2_swapped7_reg),
    .QN(_178_)
  );
  (* src = "sbox.v:440.5-541.8" *)
  DFF_X1 _414_ (
    .CK(clk),
    .D(u11_HPC2_swapped7),
    .Q(u11_HPC2_swapped7_reg),
    .QN(_179_)
  );
  (* src = "sbox.v:440.5-541.8" *)
  DFF_X1 _415_ (
    .CK(clk),
    .D(o2_val_0),
    .Q(z673_assgn6730),
    .QN(_180_)
  );
  (* src = "sbox.v:440.5-541.8" *)
  DFF_X1 _416_ (
    .CK(clk),
    .D(z673_assgn6730),
    .Q(z673_assgn6731),
    .QN(_181_)
  );
  (* src = "sbox.v:440.5-541.8" *)
  DFF_X1 _417_ (
    .CK(clk),
    .D(o2_val_1),
    .Q(z675_assgn6750),
    .QN(_182_)
  );
  (* src = "sbox.v:440.5-541.8" *)
  DFF_X1 _418_ (
    .CK(clk),
    .D(z675_assgn6750),
    .Q(z675_assgn6751),
    .QN(_183_)
  );
  (* src = "sbox.v:440.5-541.8" *)
  DFF_X1 _419_ (
    .CK(clk),
    .D(o3_val_0),
    .Q(z677_assgn6770),
    .QN(_184_)
  );
  (* src = "sbox.v:440.5-541.8" *)
  DFF_X1 _420_ (
    .CK(clk),
    .D(o3_val_1),
    .Q(z679_assgn6790),
    .QN(_185_)
  );
  (* src = "sbox.v:440.5-541.8" *)
  DFF_X1 _421_ (
    .CK(clk),
    .D(o5_val_0),
    .Q(z685_assgn6850),
    .QN(_186_)
  );
  (* src = "sbox.v:440.5-541.8" *)
  DFF_X1 _422_ (
    .CK(clk),
    .D(z685_assgn6850),
    .Q(z685_assgn6851),
    .QN(_187_)
  );
  (* src = "sbox.v:440.5-541.8" *)
  DFF_X1 _423_ (
    .CK(clk),
    .D(o5_val_1),
    .Q(z687_assgn6870),
    .QN(_188_)
  );
  (* src = "sbox.v:440.5-541.8" *)
  DFF_X1 _424_ (
    .CK(clk),
    .D(z687_assgn6870),
    .Q(z687_assgn6871),
    .QN(_189_)
  );
  (* src = "sbox.v:440.5-541.8" *)
  DFF_X1 _425_ (
    .CK(clk),
    .D(o6_val_0),
    .Q(z689_assgn6890),
    .QN(_190_)
  );
  (* src = "sbox.v:440.5-541.8" *)
  DFF_X1 _426_ (
    .CK(clk),
    .D(z689_assgn6890),
    .Q(z689_assgn6891),
    .QN(_191_)
  );
  (* src = "sbox.v:440.5-541.8" *)
  DFF_X1 _427_ (
    .CK(clk),
    .D(o6_val_1),
    .Q(z691_assgn6910),
    .QN(_192_)
  );
  (* src = "sbox.v:440.5-541.8" *)
  DFF_X1 _428_ (
    .CK(clk),
    .D(z691_assgn6910),
    .Q(z691_assgn6911),
    .QN(_193_)
  );
  (* src = "sbox.v:440.5-541.8" *)
  DFF_X1 _429_ (
    .CK(clk),
    .D(o7_val_0),
    .Q(z693_assgn6930),
    .QN(_194_)
  );
  (* src = "sbox.v:440.5-541.8" *)
  DFF_X1 _430_ (
    .CK(clk),
    .D(o7_val_1),
    .Q(z695_assgn6950),
    .QN(_095_)
  );
  assign a_share_neg_hpc3_w_1_order1_HPC30 = i6_1;
  assign a_share_neg_hpc3_w_1_order1_HPC31 = i3_1;
  assign a_share_neg_hpc3_w_1_order1_HPC32 = i2_1;
  assign n1_0 = i1_0;
  assign n2_0 = i2_0;
  assign n3_0 = i3_0;
  assign n6_0 = i6_0;
  assign n7_0 = i7_0;
  assign t0_0 = nt0_0;
  assign t2_0 = nt2_0;
  assign t4_0 = nt4_0;
  assign z673_assgn673 = o2_val_0;
  assign z675_assgn675 = o2_val_1;
  assign z677_assgn677 = o3_val_0;
  assign z679_assgn679 = o3_val_1;
  assign z685_assgn685 = o5_val_0;
  assign z687_assgn687 = o5_val_1;
  assign z689_assgn689 = o6_val_0;
  assign z691_assgn691 = o6_val_1;
  assign z693_assgn693 = o7_val_0;
  assign z695_assgn695 = o7_val_1;
endmodule
